version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
  build:
    commands:
      - echo "Building application (if any)..."
      - echo "Simulating build output..."
      - mkdir -p build_output
      - echo "Hello from CodeBuild!" > build_output/index.html
artifacts:
  files:
    - build_output/index.html
    - appspec.yml # <<< ADD THIS LINE
  discard-paths: no
